services:
  mariadb:
    image: mariadb:latest
    container_name: my_eshop_mariadb
    ports:
      - "3310:3306"
    environment:
      MARIADB_DATABASE: my_eshop_db
      MARIADB_ROOT_PASSWORD: Abcd1234
    volumes:
      - my_eshop_mariadb_data:/var/lib/mysql
      - my_eshop_mariadb_logs:/var/log/mysql
      - my_eshop_mariadb_conf:/etc/mysql/conf.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_es_0900_ai_ci

volumes:
  my_eshop_mariadb_data:
  my_eshop_mariadb_logs:
  my_eshop_mariadb_conf:
